# Generated by Django 4.1.1 on 2022-09-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Etuduiants',
            fields=[
                ('matricule', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('addressParent', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('montant', models.PositiveIntegerField()),
                ('typeFrais', models.CharField(max_length=15)),
                ('idAnneAcademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarite.anneeacademique')),
            ],
        ),
        migrations.CreateModel(
            name='Specialites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datePayement', models.DateField()),
                ('montant', models.PositiveIntegerField()),
                ('nature', models.CharField(max_length=15)),
                ('idFrais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarite.frais')),
                ('matriculeEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarite.etuduiants')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numNiveau', models.PositiveIntegerField()),
                ('idSpecialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarite.specialites')),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateInscription', models.DateField()),
                ('montant', models.PositiveIntegerField()),
                ('matriculeEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarite.etuduiants')),
            ],
        ),
        migrations.AddField(
            model_name='etuduiants',
            name='idSpecialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarite.specialites'),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numClass', models.PositiveIntegerField()),
                ('idNiveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarite.niveau')),
            ],
        ),
    ]
