# Generated by Django 4.1.1 on 2022-09-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0002_rename_numclass_classe_numclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='idClasse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Scolarite.classe'),
            preserve_default=False,
        ),
    ]
