# Generated by Django 4.1.1 on 2022-09-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0003_inscriptions_idclasse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etuduiants',
            new_name='Etudiants',
        ),
    ]
