# Generated by Django 4.1.1 on 2022-09-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0004_rename_etuduiants_etudiants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiants',
            name='idSpecialite',
        ),
    ]
