# Generated by Django 4.1.1 on 2022-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0005_remove_etudiants_idspecialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='capacite',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
