# Generated by Django 4.1.1 on 2022-09-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0006_classe_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='idNiveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scolarite.niveau'),
            preserve_default=False,
        ),
    ]
