# Generated by Django 4.1.1 on 2022-09-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0007_inscriptions_idniveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiants',
            name='idSpecialite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scolarite.specialites'),
            preserve_default=False,
        ),
    ]
