# Generated by Django 4.1.1 on 2022-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0008_etudiants_idspecialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='numClasse',
        ),
        migrations.AddField(
            model_name='classe',
            name='nom',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
