# Generated by Django 4.1.1 on 2022-10-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0009_remove_classe_numclasse_classe_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiants',
            old_name='address',
            new_name='adresse',
        ),
    ]
