# Generated by Django 4.1.1 on 2022-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0010_rename_address_etudiants_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiants',
            name='telephone',
            field=models.PositiveIntegerField(default=657764696),
            preserve_default=False,
        ),
    ]
