# Generated by Django 4.1.1 on 2022-10-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0011_etudiants_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiants',
            name='idSpecialite',
        ),
    ]
