# Generated by Django 4.1.1 on 2022-10-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0012_remove_etudiants_idspecialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptions',
            name='idClasse',
        ),
        migrations.AddField(
            model_name='inscriptions',
            name='idSpecialite',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Scolarite.specialites'),
            preserve_default=False,
        ),
    ]
