# Generated by Django 4.1.1 on 2022-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0013_remove_inscriptions_idclasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiants',
            name='email',
            field=models.EmailField(default='arsenelontsi660@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
