# Generated by Django 4.1.1 on 2022-10-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0014_etudiants_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiants',
            name='telephone',
        ),
    ]
