# Generated by Django 4.1.1 on 2022-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarite', '0015_remove_etudiants_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payements',
            name='nature',
        ),
        migrations.AlterField(
            model_name='frais',
            name='typeFrais',
            field=models.CharField(max_length=50),
        ),
    ]
